name: Ruby

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        gem: ['psych', 'rubocop']
        os: ['ubuntu-20.04', 'ubuntu-22.04']
        ruby-version: ['2.6', '2.7', '3.0', '3.1', '3.2']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - run: ruby -v
    - run: gem install ${{ matrix.gem }}
